### ISSUE TITLE
strange diff with smartcrop.js 

### ISSUE THREAD

**Issue by DaniilSokolyuk** [softawaregmbh/smartcrop.net#1]
Photo in smartcrop.js
![image](https://user-images.githubusercontent.com/2946286/51545054-3e30c780-1e72-11e9-888c-aa6091563754.png)
Photo in smartcrop.net
![image](https://user-images.githubusercontent.com/2946286/51545216-8f40bb80-1e72-11e9-886d-6b634309e573.png)

Original
![333](https://user-images.githubusercontent.com/2946286/51545020-2f4a1500-1e72-11e9-8ad5-408d88cb7b69.jpg)

**Comment by DaniilSokolyuk** [comment]
with RuleOfThirds = false looks ok

**Comment by Skleni** [comment]
Sorry for the late answer, somehow I didn't get notified (or I missed it). Is this still an issue?
