### ISSUE TITLE
Image format causes inverted y-coordinates in crop result

### ISSUE THREAD

**Issue by SaberSnail** [softawaregmbh/smartcrop.net#4]
I used the Smartcrop.Sample.Wpf application on the following image to crop to 194px wide by 109px high:
![Charles Spurgeon](https://user-images.githubusercontent.com/16519171/92644887-dde5d800-f298-11ea-9f29-577b8b7a7eed.jpg)

The resulting crop was unexpected:
![BadCrop](https://user-images.githubusercontent.com/16519171/92645101-34531680-f299-11ea-850d-503601cf3dca.png)

After some debugging, I noticed that the y-coordinate of the cropping location appeared to be inverted.

At some point, I ended up converting this image to a png file:
![Charles Spurgeon](https://user-images.githubusercontent.com/16519171/92645208-58165c80-f299-11ea-9932-f18c04ffb723.png)

When I used the sample application on this image with the same crop size, the coordinates came out as expected:
![GoodCrop](https://user-images.githubusercontent.com/16519171/92645452-b6dbd600-f299-11ea-81f0-223b24959279.png)

I can't see any obvious reason why the two images would crop differently.

**Comment by Skleni** [comment]
If you compare the color values of the two images, they're not exactly the same. For example, the top left pixel in the jpg has the color `#2C2535` while the same pixel's color in the png is `#2D2735`.

The different colors result in different scores:

Here are the scores for the area containing the face for jpg (left) and png (right):

![image](https://user-images.githubusercontent.com/10420514/92692148-04148200-f344-11ea-8aa1-49a9a7a258c6.png)

And for the area containing the hands:

![image](https://user-images.githubusercontent.com/10420514/92688289-628a3200-f33d-11ea-9761-8cc9b45e0dda.png)

Apparently the slightly different jpg colors get a better score in the skin category for the hands.

The [original implementation](https://github.com/jwagner/smartcrop.js) seems to have the same issue. Depending on your needs, you might be able to achieve better results by using different weights for the individual scores.

**Comment by SaberSnail** [comment]
Thanks for looking into this.
