### ISSUE TITLE
Face tracking

### ISSUE THREAD

**Issue by CraigChamberlain** [softawaregmbh/smartcrop.net#7]
Hi,

I'm not getting a great performance on the face centring.  It's not really clear how to go about altering the settings for the boost for example to make this work.  Should it focus on faces out of the box or does this need to be turned on. What options would you recommend switching up to start with?

**Comment by Skleni** [comment]
Hi, sorry for the late response. Out of the box, there is no face detection (other than trying to prioritize areas with skin color, see https://github.com/jwagner/smartcrop.js/issues/9 for further information). If you need more than that, you need to use another library or service for detecting faces. You can then pass in the coordinates of the faces that were detected as boost areas. The weight of a boost area determines how important you consider it.
